/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf5153.battleship.interfaceGraphique;

/**
 *
 * @author 0-pc
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJouerSeul = new javax.swing.JButton();
        btnChargerPartie = new javax.swing.JButton();
        btnVoirRecord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        btnJouerSeul.setText("Nouvelle partie");
        btnJouerSeul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJouerSeulActionPerformed(evt);
            }
        });
        getContentPane().add(btnJouerSeul);
        btnJouerSeul.setBounds(330, 430, 140, 32);

        btnChargerPartie.setText("Charger une partie");
        btnChargerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargerPartieActionPerformed(evt);
            }
        });
        getContentPane().add(btnChargerPartie);
        btnChargerPartie.setBounds(330, 460, 140, 32);

        btnVoirRecord.setText("Meilleure score");
        btnVoirRecord.setActionCommand("Meilleure record");
        btnVoirRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoirRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoirRecord);
        btnVoirRecord.setBounds(330, 490, 140, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu_fond.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 800, 600);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nuage_fond.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-270, 0, 1070, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJouerSeulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJouerSeulActionPerformed
        FenetreChoisirDifficulte fenetreChoix = new FenetreChoisirDifficulte();
        fenetreChoix.pack();
        fenetreChoix.setLocationRelativeTo(null);
        fenetreChoix.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJouerSeulActionPerformed

    private void btnChargerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargerPartieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChargerPartieActionPerformed

    private void btnVoirRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoirRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoirRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal menu = new MenuPrincipal();
                menu.pack();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChargerPartie;
    private javax.swing.JButton btnJouerSeul;
    private javax.swing.JButton btnVoirRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
